name: Build template

on:
  push:
    branches:
      - master
  pull_request:
  registry_package:

jobs:
  build-template:
    name: Build template
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build pdf
        run: latexmk -pdflua ./template.tex

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: template.pdf
          path: ./template.pdf

      - name: Upload log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: template.log
          path: ./template.log

      - name: Build user guide
        run: latexmk -pdflua manual/moderncv_userguide.tex

      - name: Upload user guide pdf
        uses: actions/upload-artifact@v4
        with:
          name: moderncv_userguide.pdf
          path: manual/moderncv_userguide.pdf

      - name: Upload user guide log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: moderncv_userguide.log
          path: manual/moderncv_userguide.log
